spring.application.name=cloud

spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare
spring.data.mongodb.auto-index-creation=true


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://faithful-ant-60.clerk.accounts.dev
clerk.jwks.url=https://faithful-ant-60.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_BKEnKw5gNaZS3ZaxpFJx3uzGbmkmOFyZ

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=25MB


razorpay.key.secret=UV7tambl09jUoOsTfcS7BPTT
razorpay.key.id=rzp_test_fIqKmW4q5aSeP0




